---
title: "2019-03-27-yinghsuan726"
output: html_document
---

```{r}
library(lubridate)
dtObject<-ymd_hms("1970-01-01 00:02:53") 
dtObject
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
twDateTime
```
```{r}
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
LisbonDateTime
```

##excersice
```{r}
Bangkoktime<-with_tz(twDateTime,tzone="Asia/Bangkok")
Bangkoktime
```
```{r}
typeof(twDateTime)
as.double(twDateTime)
```
```{r}
typeof(LisbonDateTime)
as.double(LisbonDateTime)
```
```{r}
typeof(Bangkoktime)
as.double(Bangkoktime)
```

```{r}
mytime<-ymd_hms("2019-03-27 15:49:00")
mytime
as.double(mytime)
```

```{r}
as.integer(ymd_hms("1970-01-01 00:00:01"))
as.integer(ymd_hms("1970-01-02 00:00:01"))
as.double(ymd("1970-01-01"))
as.double(ymd("1970-01-02"))
```
請讓電腦理解以下兩種日期：

“2018-09-11”

“March 3, 2019”
```{r}
ymd("2018-09-11")
mdy("March 3, 2019")
```

#5-1
```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
```

```{r}
a+b
a+bL
```

請問a+bL與aL+bL的class分別是什麼？如果用-和*呢？
```{r}
class(a+bL)
class(aL+bL)
a-bL
a/bL
aL-bL
aL/bL
```

```{r}
c <- 4

c+a
```

```{r}
a%%aL
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
twDateTime +1
```

請計算“2019-08-11”與“2000-02-01”的兩個日期的相減。相減完之後的值具有什麼class?
```{r}
ymd("2019-08-11")->z
ymd("2000-02-01")->x
z-x
class(z-x)
```

```{r}
x=1
x

```
```{r}
x <- 5
y <- 7
x==y
x!=y
```
```{r}
x2 <- c(1,5,10)
y2 <- c(-1,5,20)
x2==y2
```

```{r}
x3 <- c("小明","小花")
y3 <- c("小明","小華")
x3==y3
x3!=y3
```

```{r}
x4 <- c(1,5,8)
y4 <- c(5,8)

x4 %in% y4
```

```{r}
x5 <- c("台北市","新北市","高雄市")
y5 <- c("台北市","新北市")

x5 %in% y5
```
```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")
is.na(x2)
sum(x2)
```

