---
title: '2019-03-20'
author: "yinghsuan726"
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep="\n")
```
```{r}
studentMajors1<- c("經濟系", "經濟系", "法律系")
```
```{r}
class(studentMajors1)
```

```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系")
)
```
```{r}
class(studentMajors)
```

```{r}
levels(studentMajors)
```
```{r}
as.integer(studentMajors)
```
```{r}
BirthPlace<-factor(c("台北市","台中市","台中市","台北市","台北市"))

BirthPlace
as.integer(BirthPlace)
levels(BirthPlace)
is.factor(BirthPlace)
as.factor(BirthPlace)

```



```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) # 無法進行數值運算
stringInteger 

trueInteger <- as.integer(stringInteger)
class(trueInteger) # 可以進行數值運算
trueInteger
```

```{r}
library(lubridate)
#雖然R本身有時間處理的相關函數，但最好用的還是lubridate這個套件
dtObject<-ymd_hms("1970-01-01 00:02:53") 
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
class(dtObject)
#POSIX=跨作業系統的協定時間
#若未更改設定 電腦會自動判斷我們位於經度0度的位置
```




```{r}
typeof(dtObject)

#typeof可看出電腦用什麼方式儲存 
#double=非整數之意
```
#顯示目前電腦時區設定
```{r}
Sys.timezone()
#可測得電腦位於什麼時區
```
```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
```

